# Generated by Django 5.2.9 on 2025-12-02 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoface', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
                ('puntos', models.IntegerField(default=0)),
                ('motivo', models.CharField(max_length=200)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='autoface.cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Facepres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=200)),
                ('movimientos', models.ManyToManyField(to='autoface.movimiento')),
            ],
        ),
    ]
