# Generated by Django 5.2.9 on 2025-12-03 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoface', '0002_movimiento_facepres'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facepres',
            options={'verbose_name_plural': 'Facepres'},
        ),
        migrations.CreateModel(
            name='ConciliacionMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(help_text='Mes/Año de la liquidación')),
                ('archivo_excel', models.FileField(upload_to='conciliaciones/')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Procesar'), ('PROCESADA', 'Procesada'), ('REVISADA', 'Completamente Revisada')], default='PENDIENTE', max_length=20)),
                ('total_registros', models.IntegerField(default=0)),
                ('total_coincidencias', models.IntegerField(default=0)),
                ('total_discrepancias', models.IntegerField(default=0)),
                ('usuario_carga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conciliación Mensual',
                'verbose_name_plural': 'Conciliaciones Mensuales',
                'ordering': ['-periodo'],
            },
        ),
        migrations.CreateModel(
            name='RegistroLiquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legajo', models.CharField(max_length=200)),
                ('nombre_completo', models.CharField(max_length=400)),
                ('codigo_cargo', models.CharField(max_length=200)),
                ('puntos_liquidados', models.IntegerField()),
                ('estado_matching', models.CharField(default='PENDIENTE', max_length=20)),
                ('cargo_sistema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='autoface.cargo')),
                ('conciliacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='autoface.conciliacionmensual')),
            ],
            options={
                'verbose_name': 'Registro de Liquidación',
                'verbose_name_plural': 'Registros de Liquidación',
            },
        ),
        migrations.CreateModel(
            name='Discrepancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PAGO_SIN_AUTORIZACION', 'Se pagó sin autorización'), ('NO_PAGO_AUTORIZADO', 'No se pagó cargo autorizado'), ('DIFERENCIA_PUNTOS', 'Diferencia en puntos'), ('CARGO_NO_ENCONTRADO', 'Cargo no encontrado en sistema')], max_length=30)),
                ('descripcion', models.TextField()),
                ('puntos_esperados', models.IntegerField(blank=True, null=True)),
                ('puntos_liquidados', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente Revisión'), ('REVISADA', 'Revisada')], default='PENDIENTE', max_length=20)),
                ('comentario_revision', models.TextField(blank=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='autoface.cargo')),
                ('conciliacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discrepancias', to='autoface.conciliacionmensual')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discrepancias_revisadas', to=settings.AUTH_USER_MODEL)),
                ('registro_liquidacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autoface.registroliquidacion')),
            ],
            options={
                'verbose_name': 'Discrepancia',
                'verbose_name_plural': 'Discrepancias',
                'ordering': ['estado', '-fecha_revision'],
            },
        ),
    ]
